# Generated by Django 2.0.5 on 2019-06-11 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footer',
            old_name='about',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='author',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='cookies',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='privacy',
        ),
    ]
