# Generated by Django 2.0.5 on 2019-06-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20190612_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='photo',
            field=models.ImageField(default='pic_slider/None/no-img.jpg', upload_to='pic_slider/'),
        ),
    ]
