# Generated by Django 2.0.5 on 2019-06-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20190612_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='description',
            field=models.CharField(default='Lorem ipsum. Lorem ipsum.', max_length=100),
        ),
    ]
