# Generated by Django 2.2.3 on 2019-07-03 08:32

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190614_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(blank='True', max_length=500),
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(blank='True', max_length=250),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=tinymce.models.HTMLField(blank='True', max_length=5000),
        ),
    ]
