# Generated by Django 2.1.5 on 2019-06-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_auto_20190614_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='lead',
            field=models.TextField(default='descritpion', max_length=245),
        ),
        migrations.AddField(
            model_name='slider',
            name='link',
            field=models.URLField(default='', max_length=20000),
        ),
    ]
