# Generated by Django 2.1.5 on 2019-07-03 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_auto_20190620_2041'),
        ('cms', '0008_auto_20190703_1032'),
    ]

    operations = [
    ]
