# Generated by Django 2.1.5 on 2019-07-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_merge_20190703_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='lead',
        ),
        migrations.AlterField(
            model_name='footer',
            name='link',
            field=models.URLField(default='', max_length=20000),
        ),
        migrations.AlterField(
            model_name='slider',
            name='link',
            field=models.URLField(blank='True', max_length=250),
        ),
    ]
